from django.urls import path
from . import views

urlpatterns = [
    path('adminpanel',views.adminindex,name="adminindex"),
    path('fetchregdata',views.fetchregdata,name="fetchregdata"),
    # path('fetchlogindata',views.fetchlogindata,name="fetchlogindata"),
    path('userdatatable',views.userdatatable,name="userdatatable"),
    path('usersensordata',views.usersensordata,name="usersensordata"),
    path('waterleveldata',views.waterdatatable,name="waterleveldata"),
    path('securitydata',views.securitydatatable,name="securitydata"),
    path('soildata',views.soildatatable,name="soildata"),
    path('raindata',views.raindatatable,name="raindata"),
    path('flamedata',views.flamedatatable,name="flamedata"),
    path('complaints',views.complaints,name="complaints"),



    path('auth-confirm', views.authconfirm, name="authconfirm"),
    path('auth-login', views.authlogin, name="authlogin"),
    path('auth-login-half', views.authloginhalf, name="authlogin-half"),
    path('auth-register', views.authregister, name="authregister"),
    path('auth-resetpw', views.authresetpw, name="authresetpw"),
    path('calendar', views.calendar, name="calendar.html"),
    path('chartapexcharts', views.chartapexchart, name="chart-apexcharts.html"),
    path('chartchartjs', views.chartchartjs, name="chart-chartjs.html"),
    path('chartinline', views.chartinline, name="chart-inline.html"),
    path('contactsgrid', views.contactsgrid, name="contacts-grid.html"),
    path('contactslist', views.contactslist, name="contacts-list.html"),
    path('contactsnew', views.contactsnew, name="contacts-new.html"),
    path('dashboardanalytics', views.dashboardanalytics, name="dashboard-analytics.html"),
    path('dashboardsaas', views.dashboardsaas, name="dashboard-saas.html"),
    path('dashboardsales', views.dashboardsales, name="dashboard-sales.html"),
    path('dashboardsystem', views.dashboardsystem, name="dashboard-system.html"),
    path('datamaps', views.datamaps, name="datamaps.html"),
    path('filesgrid', views.filesgrid, name="files-grid.html"),
    path('fileslist', views.fileslist, name="files-list.html"),
    path('formadvanced', views.formadvanced, name="form_advanced.html"),
    path('formaelements', views.formaelements, name="form_elements.html"),
    path('formlayouts', views.formlayouts, name="form_layouts.html"),
    path('formupload', views.formaupload, name="form_upload.html"),
    path('formvalidation', views.formvalidation, name="form_validation.html"),
    path('formwizard', views.formwizard, name="form_wizard.html"),
    path('indexboxed', views.indexboxed, name="index-boxed.html"),
    path('indexhorizontal', views.indexhorizontal, name="index-horizontal.html"),
    path('indexvertical', views.indexvertical, name="index-vertical.html"),
    path('page-404', views.page404, name="page-404.html"),
    path('page-500', views.page500, name="page-500.html"),
    path('pageblank', views.pageblank, name="page-blank.html"),
    path('pageinvoice', views.pageinvoice, name="page-invoice.html"),
    path('pageorders', views.pageorders, name="page-orders.html"),
    path('pagetimeline', views.pagetimeline, name="page-timeline.html"),
    path('profile', views.profile, name="profile.html"),
    path('profilenotification', views.profilenotification, name="profile-notification.html"),
    path('profilesecurity', views.profilesecurity, name="profile-security.html"),
    path('profilesettions', views.profilesettions, name="profile-settings.html"),
    path('supportecenter', views.supportecenter, name="support-center.html"),
    path('supportfaqs', views.supportfaqs, name="support-faqs.html"),
    path('supportticketdetail', views.supportticketdetail, name="support-ticket-detail.html"),
    path('supporttickets', views.supporttickets, name="support-tickets.html"),
    path('tableadvanced', views.tableadvanced, name="table_advanced.html"),
    path('tablebasic', views.tablebasic, name="table_basic.html"),
    path('tabledatatables', views.tabledatatables, name="table_datatables.html"),
    path('uibuttons', views.uibuttons, name="ui-buttons.html"),
    path('uicolor', views.uicolor, name="ui-color.html"),
    path('uiicons', views.uiicons, name="ui-icons.html"),
    path('uimodals', views.uimodals, name="ui-modals.html"),
    path('uinotification', views.uinotification, name="ui-notification.html"),
    path('uiprogress', views.uiprogress, name="ui-progress.html"),
    path('uitabsaccordation', views.uitabsaccordation, name="ui-tabs-accordion.html"),
    path('uitypograpy', views.uitypograpy, name="ui-typograpy.html"),
    path('widgets', views.widgets, name="widgets.html"),
]