from django.urls import path
from . import views
urlpatterns = [
    path('',views.index,name="indexpage"),
    path('about',views.about,name="aboutpage"),
    path('userdashboard',views.userdashboard,name="userdashboard"),
    path('complaintregister', views.complaintregister, name="complaintregister"),
    path('tablebasic', views.tablebasic, name="table_basic.html"),
    path('contact',views.contact,name="contactpage"),
    path('services',views.services,name="servicespage"),
    path('userlogin',views.userlogin,name="userlogin"),
    path('dashboard',views.dashboard,name="dashboard"),
    path('fetchlogindata',views.fetchlogindata,name="fetchlogindata"),
    path('adminlogin',views.adminlogin,name="adminlogin"),
    path('logout',views.logout,name="logout"),
    path('fetchadminlogindata',views.fetchadminlogindata,name="fetchadminlogindata"),


path('flamedatatable', views.flamedatatable, name="flamedatatable.html"),
    path('raindatatable', views.raindatatable, name="raindatatable.html"),
    path('securitydatatable', views.securitydatatable, name="securitydatatable.html"),
    path('waterlevel', views.waterdatatable, name="waterdatatable.html"),
    path('soildatatable', views.soildatatable, name="soildatatable.html"),
    path('calendar', views.calendar, name="calendar.html"),
    path('indexboxed', views.indexboxed, name="index-boxed.html"),
    path('indexhorizontal', views.indexhorizontal, name="index-horizontal.html"),
    path('indexvertical', views.indexvertical, name="index-vertical.html"),
    path('profile', views.profile, name="profile.html"),
    path('profilenotification', views.profilenotifications, name="profile-notification.html"),
    path('profilesecurity', views.profilesecurity, name="profile-security.html"),
    path('profilesettions', views.profilesettions, name="profile-settings.html"),
    path('supportecenter', views.supportecenter, name="support-center.html"),
    path('supportfaqs', views.supportfaqs, name="support-faqs.html"),
    path('supportticketdetail', views.supportticketdetail, name="support-ticket-detail.html"),
    path('supporttickets', views.supporttickets, name="support-tickets.html"),
    path('tablebasic', views.tablebasic, name="table_basic.html"),
    path('tabledatatables', views.tabledatatables, name="table_datatables.html"),
    path('contact', views.contact, name="contact.html"),
    path('smokedata',views.Smoke, name="Smoke.html"),
]